from __future__ import annotations


TOOL_ALIAS_MAP: dict[str, str] = {
    "append": "append_file",
    "append_file": "append_file",
    "create": "create_file",
    "create_file": "create_file",
    "delete": "delete_file",
    "delete_file": "delete_file",
    "remove": "delete_file",
    "remove_file": "delete_file",
    "rm": "delete_file",
    "read": "read_file",
    "read_file": "read_file",
    "readfile": "read_file",
    "write": "write_file",
    "write_file": "write_file",
    "writefile": "write_file",
    "list": "list_dir",
    "list_dir": "list_dir",
    "listdir": "list_dir",
    "gitstatus": "git_status",
    "git_status": "git_status",
    "search": "search_code",
    "search_code": "search_code",
    "searchcode": "search_code",
    "shell": "shell_cmd",
    "shell_cmd": "shell_cmd",
    "shellcmd": "shell_cmd",
    "shell_bg": "shell_bg",
    "shellbg": "shell_bg",
    "shell_background": "shell_bg",
    "background": "shell_bg",
    "shell_bg_check": "shell_bg_check",
    "shellbgcheck": "shell_bg_check",
    "bg_check": "shell_bg_check",
    "edit": "edit_file",
    "edit_file": "edit_file",
    "editfile": "edit_file",
    "replace": "edit_file",
    "patch": "edit_file",
    "diff": "diff_files",
    "show_diff": "show_diff",
    "showdiff": "show_diff",
    "git_diff": "show_diff",
    "http": "http_get",
    "http_get": "http_get",
    "fetch": "http_get",
    "get_url": "http_get",
    "image": "generate_image",
    "generate_image": "generate_image",
    "image_gen": "generate_image",
    "imagegen": "generate_image",
    "create_image": "generate_image",
    "pdf": "generate_pdf",
    "generate_pdf": "generate_pdf",
    "pdf_gen": "generate_pdf",
    "pdfgen": "generate_pdf",
    "create_pdf": "generate_pdf",
    "save_note": "remember",
    "note": "remember",
    "remember": "remember",
    "recall": "recall",
    "search_memory": "recall",
    "plan": "plan_task",
    "plan_task": "plan_task",
    "subagent": "spawn_subagent",
    "spawn_subagent": "spawn_subagent",
    "delegate": "spawn_subagent",
    "project_info": "project_info",
    "projectinfo": "project_info",
    "scan_project": "project_info",
    "analyze_project": "project_info",
    "web_search": "web_search",
    "websearch": "web_search",
    "search_web": "web_search",
    "google": "web_search",
    "duckduckgo": "web_search",
    "glob_files": "glob_files",
    "glob": "glob_files",
    "find_files": "glob_files",
    "grep_code": "grep_code",
    "rg": "grep_code",
    "ripgrep": "grep_code",
    "diff_files": "diff_files",
    "memory_write": "memory_write",
    "memorize": "memory_write",
    "save_memory": "memory_write",
    "memory_read": "memory_read",
    "recall_memory": "memory_read",
    "load_memory": "memory_read",
    # ── Browser automation ──
    "browser_navigate": "browser_navigate",
    "navigate": "browser_navigate",
    "browse": "browser_navigate",
    "open_url": "browser_navigate",
    "browser_screenshot": "browser_screenshot",
    "screenshot": "browser_screenshot",
    "capture": "browser_screenshot",
    "browser_inspect": "browser_inspect",
    "inspect_page": "browser_inspect",
    "dom_inspect": "browser_inspect",
    "browser_click": "browser_click",
    "click": "browser_click",
    "browser_type": "browser_type",
    "type_text": "browser_type",
    "browser_scroll": "browser_scroll",
    "scroll": "browser_scroll",
    "browser_evaluate": "browser_evaluate",
    "browser_eval": "browser_evaluate",
    "js_eval": "browser_evaluate",
}


TOOL_ARG_EXAMPLES: dict[str, str] = {
    "shell_cmd": '{"cmd": "ls -la", "cwd": "~/project"}',
    "shell_bg": '{"cmd": "npm run dev", "cwd": "~/project"}',
    "read_file": '{"path": "~/project/src/app.tsx"}',
    "write_file": '{"path": "~/project/file.ts", "content": "file contents here"}',
    "edit_file": '{"path": "~/project/file.ts", "old_string": "exact old text", "new_string": "replacement text"}',
    "search_code": '{"pattern": "function_name", "path": "~/project"}',
    "list_dir": '{"path": "~/project/src"}',
    "delete_file": '{"path": "~/project/old_file.ts"}',
    "git_status": '{"path": "~/project"}',
    "show_diff": '{"path": "~/project"}',
    "http_get": '{"url": "http://localhost:3000"}',
    "generate_image": '{"prompt": "A clean isometric landing page hero illustration of a futuristic AI workspace", "aspect_ratio": "16:9", "image_size": "1K"}',
    "generate_pdf": '{"title": "Quarterly Update", "sections": [{"heading": "Summary", "paragraphs": ["Revenue grew 18 percent quarter over quarter."], "bullets": ["Retention up", "Pipeline expanded"]}]}',
    "plan_task": '{"goal": "Fix the login page", "steps": ["Read the file", "Find the bug", "Fix it"]}',
    "remember": '{"key": "db_url", "value": "postgres://localhost/mydb"}',
    "recall": '{"query": "database"}',
    "glob_files": '{"pattern": "**/*.tsx", "path": "~/project"}',
    "browser_navigate": '{"url": "http://localhost:3000"}',
    "browser_screenshot": '{}',
    "browser_inspect": '{}',
    "browser_click": '{"selector": "button.submit"}',
    "browser_type": '{"selector": "input#email", "text": "hello@example.com"}',
    "browser_scroll": '{"direction": "down", "pixels": 500}',
    "browser_evaluate": '{"expression": "document.querySelector(\'.header\').getBoundingClientRect()"}',
}


__all__ = ["TOOL_ALIAS_MAP", "TOOL_ARG_EXAMPLES"]
