from __future__ import annotations

import aiosqlite

from .activity import get_activity, log_event
from .chat import clear_chat_history, get_chat_history, save_message
from .core import DB_PATH, get_db, init_db
from .memory import (
    count_memory_items_by_layer,
    delete_stale_memory_items,
    get_memory_item,
    get_memory_item_by_key,
    list_memory_items,
    list_memory_items_filtered,
    list_memory_links,
    touch_memory_item,
    update_memory_item_state,
    upsert_memory_item,
    upsert_memory_link,
)
from .projects import (
    get_project,
    get_projects,
    update_project_note,
    update_project_status,
    upsert_project,
)
from .prompts import (
    delete_prompt,
    get_prompt,
    get_prompts,
    increment_prompt_usage,
    save_prompt,
)
from .research_packs import (
    add_research_pack_items,
    create_research_pack,
    delete_research_pack,
    get_research_pack,
    get_research_pack_items,
    list_research_packs,
    remove_research_pack_item,
    update_research_pack,
)
from .resources import (
    add_resource,
    delete_resource,
    get_resource,
    get_resource_chunks,
    get_resources_by_ids,
    list_resources,
    replace_resource_chunks,
    touch_resource_used,
    update_resource,
)
from .settings import get_all_settings, get_setting, set_setting
from .tasks import add_task, delete_task, get_tasks, update_task, update_task_status
from .terminal import (
    add_terminal_event,
    create_terminal_session,
    get_terminal_session,
    list_terminal_events,
    list_terminal_sessions,
    mark_terminal_sessions_stopped,
    update_terminal_session,
)
from .webhooks import (
    enqueue_webhook,
    get_pending_webhooks,
    mark_webhook_failed,
    mark_webhook_sent,
)

__all__ = [
    "DB_PATH",
    "aiosqlite",
    "get_db",
    "init_db",
    "upsert_project",
    "get_projects",
    "get_project",
    "update_project_note",
    "update_project_status",
    "save_prompt",
    "get_prompts",
    "increment_prompt_usage",
    "delete_prompt",
    "get_prompt",
    "add_task",
    "get_tasks",
    "update_task_status",
    "update_task",
    "delete_task",
    "log_event",
    "get_activity",
    "save_message",
    "get_chat_history",
    "clear_chat_history",
    "get_setting",
    "set_setting",
    "get_all_settings",
    "add_resource",
    "update_resource",
    "list_resources",
    "get_resource",
    "get_resources_by_ids",
    "delete_resource",
    "replace_resource_chunks",
    "get_resource_chunks",
    "touch_resource_used",
    "upsert_memory_item",
    "get_memory_item",
    "get_memory_item_by_key",
    "list_memory_items",
    "delete_stale_memory_items",
    "touch_memory_item",
    "count_memory_items_by_layer",
    "update_memory_item_state",
    "list_memory_items_filtered",
    "create_research_pack",
    "list_research_packs",
    "get_research_pack",
    "update_research_pack",
    "delete_research_pack",
    "add_research_pack_items",
    "remove_research_pack_item",
    "get_research_pack_items",
    "upsert_memory_link",
    "list_memory_links",
    "create_terminal_session",
    "list_terminal_sessions",
    "get_terminal_session",
    "update_terminal_session",
    "mark_terminal_sessions_stopped",
    "add_terminal_event",
    "list_terminal_events",
    "enqueue_webhook",
    "get_pending_webhooks",
    "mark_webhook_sent",
    "mark_webhook_failed",
]
